version: '2'
plugins:
  editorconfig:
    enabled: true
  tslint:
    enabled: false
  eslint:
    enabled: true
    config:
      config: .eslintrc-cc.json
  fixme:
    enabled: true
  git-legal:
    enabled: true
exclude_patterns:
  - '**/.github'
  - '**/.circleci'
  - '**/.vscode'
  - '**/dist'
  - '**/temp'
  - '**/test'
  - '**/docs'
  - '**/node_modules/'
  - '**/fixtures'
  - '**/.husky'
  - '**/commitlint.config.js'
