version: '2'
plugins:
  duplication:
    enabled: true
  editorconfig:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-7"
    config:
      config: .eslintrc-cc.json
    extensions:
      - .ts
      - .js
      - .mjs
  fixme:
    enabled: true
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
  structure:
    enabled: true
exclude_patterns:
  - '**/.github'
  - '**/.husky'
  - '**/.vscode'
  - '**/fixtures'
  - '**/dist'
  - '**/test'
  - '**/node_modules'
