name: 'NodeJS Project Information'
description: 'Provides project information based on package.json'
author: 'Gregor Anders <gregor.ander@gmail.com>'
inputs:
  path:
    description: 'Path to package.json'
    required: false
    default: './package.json'
outputs:
  context:
    description: 'Serialized package.json'
  name:
    description: 'Project Name'
  version:
    description: 'Project Version'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'package'
  color: 'red'
